// <auto-generated />
using System;
using Blog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blog.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    [Migration("20251102115426_AddingContentText5")]
    partial class AddingContentText5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Blog.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ContentText1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContentText2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContentText3")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContentText4")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContentText5")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImageFileName1")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageFileName2")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl1")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl2")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("Blog.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@proequipment.sa",
                            PasswordHash = "$2a$11$LLdkDB6eHoXK91a.vf2tlu6bctjoe.FEJfiwI3Bqu0H7Zl8CqnNei",
                            Username = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
